#! /bin/bash
# $Id$
# Remove backup files (*~) and, optionally, *.pyc

hflag=no # help
nflag=no # dry run - do not delete files
rflag=no # recursion
pflag=no # pyc - consider .pyc file
vflag=no # verbose (performs delete anyway)
aflag=no # all - flags r + p

# Colors
# http://en.wikipedia.org/wiki/ANSI_escape_code#CSI_Codes
esc_red='\033[91m'
esc_green='\033[92m'
esc_reset='\033[0m'

# Regexp
# if [ `uname -s` = "Linux" ]; then
    # regexp="-regextype posix-extended"
# else
    # regexp='-E'
# fi


####################################################################################
# GETOPT

# set -- $(getopt hnrplad: "$@")
set -- $(getopt hnrpva "$@")
while [ $# -gt 0 ]
do
    case "$1" in
    -h) hflag=yes;;
    -n) nflag=yes;;
    -r) rflag=yes;;
    -p) pflag=yes;;
    -v) vflag=yes;;
    -a) pflag=yes; rflag=yes;;
    --) shift; break;;
    -*) echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
    *)  break;;
    esac
    shift
done

directory=${1:-$PWD}
if [ ! -d $directory ]; then
    echo "$directory is not a directory!"
    exit 1
fi

####################################################################################
# HELP FLAG
# print help and exit

if [ $hflag = yes ]; then
	echo "Usage: bak [-vrpan] [DIRECTORY]"
    echo "  Deletes backup files ( *~ )"
    echo "  If no DIRECTORY deletes in current directory"
    echo
    echo "Options:"
    echo "   -r     Recursive"
    echo "   -p     Delete also .pyc"
    echo "   -v     Be verbose"
    echo "   -n     Dry run (no delete)"
    echo "   -a     All, alias for -pr"
	echo
    exit 0
fi

####################################################################################
# PREPARE

# Recursion
depth='-maxdepth 1'
andits=''
delete='-delete'
mask="-regex .*~$"

# Recursive
if [ $rflag = yes ]; then
    depth='' #recursive
    andits=' and its subdirectories'
fi

# Dry run
if [ $nflag = yes ]; then
    delete=''
fi

# Process pyc
if [ $pflag = yes ]; then
    mask="-regex .*~|.*\.pyc"
fi


####################################################################################
# EXEC

FILES=`find $directory $depth $mask $delete -print`
if [ -z $FILES ]; then # No files found
    FILES=''
    COUNT=0
else
    COUNT=`echo $FILES|wc -l|sed 's/[ ]*//'`
fi

if [ $vflag = yes ]; then
    cat<<EOB
$FILES
EOB
fi

if [ $COUNT -gt 0 ]; then
    echo -ne "$COUNT backup files "
    if [ $nflag = yes ]; then
        echo -n "would be "
    fi
    echo -e "${esc_red}deleted${esc_reset} in ${esc_green}$directory${esc_reset}$andits"
else
    echo -e "No backup files listed in ${esc_green}$directory${esc_reset}$andits"
fi

exit 0
