#!/bin/sh
# -*- coding: latin-1 -*-

# Copyright by Andrea Mistrali <am@am.cx>
#
# Synopsis:  Delete old EasyLink messages
#
# $Id$
# DEBUG="echo"
DIR="$MAILC/__public__/maildir/ops/EasyLink/cur"
LIST=`find $DIR -ctime +7`
DELETABLE=`for file in $LIST; do grep -lE "Subject:.*(/Ack|/Rec|/Del)" $file; done`


for file in $DELETABLE; do
    ${DEBUG} rm $file;
done
