dn: uid={{UID}},cn=people,dc=cube,dc=lan
objectClass: person
objectClass: top
objectClass: organizationalPerson
objectClass: extensibleObject
objectClass: inetOrgPerson
cn: {{FN}}
uid: {{UID}}
givenName: {{N:NAME|}}
sn: {{N:SURNAME|FN}}
o: {{ORG|}}
mail: {{EMAIL:INTERNET:WORK|EMAIL:INTERNET:HOME|EMAIL|}}
telephoneNumber: {{TEL:WORK|TEL:HOME|}}
mobile: {{TEL:CELL|}}
postalAddress: {{ADR:WORK|ADR:HOME|}}
c: {{ADR:COUNTRY|}}
street: {{ADR:STREET|}}
l: {{ADR:CITY|}}
st: {{ADR:STATE|}}
postalCode: {{ADR:ZIP|}}
